eureka:
  instance:
    instanceId: ${spring.application.name}
#    statusPageUrlPath: /eureka/info
#    healthCheckUrlPath: /eureka/health
#    home-page-url-path: /eureka
#    status-page-url-path: /eureka/info
  server:
    waitTimeInMsWhenSyncEmpty: 0
## Uncomment if you want to exclude eureka server from registery (so you cannot use client discovery but causes better boot speed)
#  client:
#    registerWithEureka: false
#    fetchRegistry: false


# Liquibase
liquibase:
  enabled: true
  change-log: classpath:cip-server-migrations.xml

spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://127.0.0.1:3306/univoip_cip_main
